countries_data = {
    "Afghanistan": "Kabul",
    "Albania": "Tirana",
    "Georgia": "Tbilisi",
    "Germany": "Berlin",
    "India": "New Delhi",
    "Japan": "Tokyo",
    "Mexico": "Mexico City",
    "Brazil": "Brasilia",
    "Canada": "Ottawa",
    "Australia": "Canberra",
    "Italy": "Rome",
    "France": "Paris",
    "Spain": "Madrid",
    "Argentina": "Buenos Aires",
    "Egypt": "Cairo",
    "Russia": "Moscow",
    "South Africa": "Pretoria",
    "Turkey": "Ankara",
    "Saudi Arabia": "Riyadh",
    "United Kingdom": "London",
    "China": "Beijing",
    "South Korea": "Seoul",
    "Nigeria": "Abuja",
    "Greece": "Athens",
    "Pakistan": "Islamabad",
    "Thailand": "Bangkok",
    "Vietnam": "Hanoi",
    "Sweden": "Stockholm",
    "Norway": "Oslo",
    "Finland": "Helsinki",
    "Denmark": "Copenhagen",
    "Netherlands": "Amsterdam",
    "Switzerland": "Bern",
    "Belgium": "Brussels",
    "Austria": "Vienna",
    "Portugal": "Lisbon",
    "Ireland": "Dublin",
    "New Zealand": "Wellington",
    "Singapore": "Singapore",
    "Malaysia": "Kuala Lumpur",
    "Philippines": "Manila",
    "Indonesia": "Jakarta",
    "Chile": "Santiago",
    "Colombia": "Bogota",
    "Peru": "Lima",
    "Venezuela": "Caracas",
}